# Generated by Django 5.0.3 on 2024-03-16 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 16, 7, 18, 1, 566299, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
    ]
